from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.parse
import urllib.request
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

FINAL_STATUS = {"FT", "AET", "PEN"}


def now_utc() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def read_jsonl(path: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    p = Path(path)
    if not p.exists():
        return rows
    with p.open("r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            rows.append(json.loads(line))
    return rows


def write_jsonl(path: str, rows: list[dict[str, Any]]) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        for row in rows:
            fh.write(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n")


def status_short(item: dict[str, Any]) -> str | None:
    return (((item.get("fixture") or {}).get("status") or {}).get("short"))


def is_final(item: dict[str, Any]) -> bool:
    return status_short(item) in FINAL_STATUS and (item.get("goals") or {}).get("home") is not None


def make_postgame_event(queue_row: dict[str, Any], fixture_item: dict[str, Any], run_id: str) -> dict[str, Any]:
    fixture = fixture_item.get("fixture") or {}
    league = fixture_item.get("league") or {}
    teams = fixture_item.get("teams") or {}
    home = teams.get("home") or {}
    away = teams.get("away") or {}
    return {
        "event_type": "POSTGAME_FINAL_BACKFILL",
        "classification": "POSTGAME",
        "stage": "POSTGAME",
        "tier": None,
        "stake_units": None,
        "bet_eligible": False,
        "coverage": {"data_tier": "POSTGAME_BACKFILL"},
        "notes": [
            "Generated by guarded final-result backfill runner.",
            "No runtime pick/stake/tier/model change was made.",
        ],
        "backfill_source": {
            "run_id": run_id,
            "queue_reason": queue_row.get("queue_reason"),
            "source_backlog_rows": queue_row.get("source_backlog_rows"),
            "decision_lines": queue_row.get("decision_lines") or [],
        },
        "fixture": {
            "fixture_id": fixture.get("id") or queue_row.get("fixture_id"),
            "kickoff": queue_row.get("kickoff_local"),
            "league_id": league.get("id"),
            "league": league.get("name") or queue_row.get("league"),
            "country": league.get("country"),
            "season": league.get("season"),
            "home_team_id": home.get("id"),
            "home_team": home.get("name") or queue_row.get("home_team"),
            "away_team_id": away.get("id"),
            "away_team": away.get("name") or queue_row.get("away_team"),
            "status": status_short(fixture_item),
            "goals": fixture_item.get("goals"),
            "score": fixture_item.get("score"),
        },
        "result": {
            "status": status_short(fixture_item),
            "goals": fixture_item.get("goals"),
            "score": fixture_item.get("score"),
        },
    }


def api_get_fixture(fixture_id: int, api_key: str, base_url: str, timeout: int) -> dict[str, Any]:
    url = f"{base_url.rstrip('/')}/fixtures?{urllib.parse.urlencode({'id': fixture_id})}"
    req = urllib.request.Request(
        url,
        headers={
            "x-apisports-key": api_key,
            "x-rapidapi-key": api_key,
            "Accept": "application/json",
            "User-Agent": "soccer-edge-postgame-backfill/1.0",
        },
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:  # noqa: S310 - trusted API-Football endpoint from env/default
        return json.loads(resp.read().decode("utf-8"))


def run_backfill(
    queue_path: str,
    history_output: str,
    report_output: str,
    api_key: str | None,
    base_url: str,
    max_calls: int,
    execute: bool,
    timeout: int = 20,
    sleep_seconds: float = 0.2,
) -> dict[str, Any]:
    queue = read_jsonl(queue_path)
    run_id = now_utc()
    report: dict[str, Any] = {
        "schema_version": "1.0.0",
        "status": "FINAL_BACKFILL_DRY_RUN" if not execute else "FINAL_BACKFILL_EXECUTED",
        "run_id": run_id,
        "queue_path": queue_path,
        "history_output": history_output,
        "max_calls": max_calls,
        "execute": execute,
        "queue_rows": len(queue),
        "provider_calls_attempted": 0,
        "provider_calls_succeeded": 0,
        "final_results_appended": 0,
        "skipped": [],
        "errors": [],
        "safety_note": "Only fixtures?id calls are allowed. No odds, ticks, runtime pick/tier/stake/model changes are performed.",
    }

    selected = queue[: max(0, max_calls)]
    report["selected_fixture_ids"] = [row.get("fixture_id") for row in selected]
    if not execute:
        report["next_action"] = "Re-run with --execute and API_FOOTBALL_KEY available to fetch final results."
        Path(report_output).parent.mkdir(parents=True, exist_ok=True)
        with open(report_output, "w", encoding="utf-8") as fh:
            json.dump(report, fh, ensure_ascii=False, indent=2, sort_keys=True)
            fh.write("\n")
        return report

    if not api_key:
        report["status"] = "FINAL_BACKFILL_BLOCKED_NO_API_KEY"
        report["errors"].append({"reason": "missing API key", "required_env": "API_FOOTBALL_KEY"})
        Path(report_output).parent.mkdir(parents=True, exist_ok=True)
        with open(report_output, "w", encoding="utf-8") as fh:
            json.dump(report, fh, ensure_ascii=False, indent=2, sort_keys=True)
            fh.write("\n")
        return report

    events: list[dict[str, Any]] = []
    for row in selected:
        fid = int(row["fixture_id"])
        try:
            report["provider_calls_attempted"] += 1
            payload = api_get_fixture(fid, api_key=api_key, base_url=base_url, timeout=timeout)
            response = payload.get("response") or []
            if not response:
                report["skipped"].append({"fixture_id": fid, "reason": "empty_provider_response"})
                continue
            item = response[0]
            report["provider_calls_succeeded"] += 1
            if not is_final(item):
                report["skipped"].append({"fixture_id": fid, "reason": "fixture_not_final", "status": status_short(item)})
                continue
            events.append(make_postgame_event(row, item, run_id=run_id))
            report["final_results_appended"] += 1
            time.sleep(max(0.0, sleep_seconds))
        except Exception as exc:  # keep runner non-catastrophic per fixture
            report["errors"].append({"fixture_id": fid, "reason": type(exc).__name__, "message": str(exc)[:500]})

    tick = {
        "schema_version": "1.0.0",
        "generated_at_utc": run_id,
        "generated_at_local": run_id,
        "timezone": "America/Mexico_City",
        "version": "postgame-final-backfill-v1",
        "event_type": "POSTGAME_FINAL_BACKFILL_TICK",
        "events": events,
    }
    if events:
        Path(history_output).parent.mkdir(parents=True, exist_ok=True)
        with open(history_output, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(tick, ensure_ascii=False, separators=(",", ":")) + "\n")
    report["history_written"] = bool(events)
    Path(report_output).parent.mkdir(parents=True, exist_ok=True)
    with open(report_output, "w", encoding="utf-8") as fh:
        json.dump(report, fh, ensure_ascii=False, indent=2, sort_keys=True)
        fh.write("\n")
    return report


def main() -> int:
    p = argparse.ArgumentParser(description="Guarded API-Football final-result backfill for Soccer Edge pending settlement rows.")
    p.add_argument("--queue", default="soccer_edge_state/analysis/postgame_final_backfill_queue.jsonl")
    p.add_argument("--history-output", default="soccer_edge_state/history/postgame_final_backfill.jsonl")
    p.add_argument("--report-output", default="soccer_edge_state/analysis/postgame_final_backfill_run_report.json")
    p.add_argument("--base-url", default=os.getenv("API_FOOTBALL_BASE_URL", "https://v3.football.api-sports.io"))
    p.add_argument("--api-key-env", default="API_FOOTBALL_KEY")
    p.add_argument("--max-calls", type=int, default=5)
    p.add_argument("--timeout", type=int, default=20)
    p.add_argument("--sleep-seconds", type=float, default=0.2)
    p.add_argument("--execute", action="store_true", help="Actually call API-Football. Without this flag, only writes a dry-run report.")
    a = p.parse_args()
    if a.max_calls < 0 or a.max_calls > 5:
        raise SystemExit("max-calls must be between 0 and 5 for this guarded runner")
    report = run_backfill(
        queue_path=a.queue,
        history_output=a.history_output,
        report_output=a.report_output,
        api_key=os.getenv(a.api_key_env),
        base_url=a.base_url,
        max_calls=a.max_calls,
        execute=bool(a.execute),
        timeout=a.timeout,
        sleep_seconds=a.sleep_seconds,
    )
    print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
